=== zondarg/ouya-game-data/ouya-game.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://cweiske.de/ouya-game.schema.json",
    "title": "OUYA game metadata",
    "description": "Game data importable in OUYA API servers.",
    "type": "object",

    "required": [
        "packageName",
        "title",
        "releases",
        "discover",
        "media",
        "developer"
    ],
    "additionalProperties": false,
    "properties": {
        "packageName": {
            "description": "Java package names",
            "type": "string",
            "examples": [
                "com.vendor.gamename"
            ]
        },

        "title": {
            "description": "Game name",
            "type": "string"
        },

        "description": {
            "description": "Text describing the game. Newlines (CRLF) allowed",
            "type": "string"
        },

        "players": {
            "description": "How many players can play this game at the same time?",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 1
            }
        },

        "genres": {
            "description": "Categories",
            "type": "array",
            "items": {
                "type": "string",
                "uniqueItems": true,
                "enum": [
                    "Adventure",
                    "App",
                    "Arcade/Pinball",
                    "Card/Casino",
                    "Dual Stick",
                    "Entertainment",
                    "Exclusive",
                    "Fight!",
                    "FPS/Shooter",
                    "Kids List",
                    "Meditative",
                    "Multiplayer",
                    "Music",
                    "Platformer",
                    "Puzzle/Trivia",
                    "Racing",
                    "Retro",
                    "Role-Playing",
                    "Short on Time?",
                    "Sim/Strategy",
                    "Sports",
                    "Utility",
                    "Video",
                    "VIP Room",

                    "Emulator",
                    "2019 GameJam",
                    "2020 GameJam",
                    "2020 Winter GameJam",
                    "2021 Anniversary GameJam",
                    "2021 Winter GameJam",
                    "2022 Winter GameJam",
                    "2023 Anniversary GameJam",
                    "Open Source",
                    "Repackaged",
                    "Tutorials",
                    "Unlocked"
                ]
            }
        },

        "languages": {
            "description": "Language of text/audio content (ISO 639-1)",
            "type": "array",
            "items": {
                "type": "string",
                "uniqueItems": true,
                "enum": [
                    "cs",
                    "da",
                    "de",
                    "el",
                    "en",
                    "eo",
                    "es",
                    "fi",
                    "fr",
                    "hu",
                    "it",
                    "ja",
                    "ko",
                    "nl",
                    "no",
                    "pl",
                    "pt",
                    "ru",
                    "sr",
                    "sv",
                    "th",
                    "tk",
                    "uk",
                    "zh"
                ]
            }
        },

        "releases": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "versionCode",
                    "uuid",
                    "date",
                    "url",
                    "size",
                    "md5sum"
                ],
                "additionalProperties": false,
                "properties": {

                    "broken": {
                        "description": "If the download URL does not work anymore",
                        "type": "boolean",
                        "default": false
                    },

                    "name": {
                        "description": "Human readable version number",
                        "type": "string",
                        "examples": [
                            "1.6"
                        ]
                    },

                    "versionCode": {
                        "description": "APK-internal version code. Run \"aapt dump badging file.apk\", field \"versionCode\"",
                        "type": ["number", "null"]
                    },

                    "uuid": {
                        "description": "Unique ID for the release. Use uuid-gen to get one",
                        "type": "string"
                    },

                    "date": {
                        "description": "When the version has been released",
                        "type": "string",
                        "format": "date|datetime"
                    },

                    "url": {
                        "description": ".apk download link",
                        "type": "string",
                        "format": "url"
                    },

                    "size": {
                        "description": "File size in bytes",
                        "type": "number",
                        "minimum": 1
                    },

                    "md5sum": {
                        "description": "MD5 hash of the .apk file contents",
                        "type": ["string", "null"],
                        "default": null
                    },

                    "publicSize": {
                        "description": "FIXME",
                        "type": "number"
                    },

                    "nativeSize": {
                        "description": "FIXME",
                        "type": "number"
                    },

                    "cert_fingerprint": {
                        "description": "A SHA256 format fingerprint of the signing certificate that was used for this APK. Allows for authorization tracking.",
                        "type": "string",
                        "minLength": 95,
                        "maxLength": 95,
                        "pattern": "^([0-9A-F]{2}:){31}[0-9A-F]{2}$",
                        "examples": [
                            "EF:D5:B9:C0:58:C1:21:ED:97:F3:FD:89:21:12:B6:00:F6:D1:9B:C2:9B:EE:F7:47:40:0C:E0:BB:0D:25:1C:40"
                        ]
                    },

                    "cert_subject": {
                        "description": "The subject name of the signing certificate",
                        "type": "string",
                        "examples": [
                            "C = US, O = Android, CN = Android Debug",
                            "C = US, ST = CA, L = San Francisco, O = SEGA of America, OU = Mobile PD, CN = alben pedroso"
                        ]
                    },

                    "stability": {
                        "description": "What quality of a release this is",
                        "default": "stability",
                        "type": "string",
                        "enum": [
                            "alpha",
                            "beta",
                            "stable"
                        ]
                    }
                }
            }
        },

        "discover": {
            "description": "Main game image. Used in the OUYA discover store. Size 732x412",
            "type": "string",
            "format": "url"
        },

        "media": {
            "description": "Images and videos for the details and apps pages. Can be in any order. The first video is used for the app's 'video' field, all images for app's 'screenshots'.",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "type",
                    "url"
                ],
                "additionalProperties": false,
                "properties": {
                    "type": {
                        "description": "Medium type: image or video",
                        "type": "string",
                        "enum": [
                            "image",
                            "video"
                        ]
                    },
                    "url": {
                        "description": "Image URL or video URL. Vimeo and Youtube URLs supported",
                        "type": "string",
                        "format": "url"
                    },
                    "thumb": {
                        "description": "Small preview image. Size should be 852x479.",
                        "type": "string",
                        "format": "url"
                    }
                }
            }
        },

        "developer": {
            "type": "object",
            "required": [
                "name"
            ],
            "additionalProperties": false,
            "properties": {

                "uuid": {
                    "description": "Unique ID for the developer",
                    "type": ["string", "null"],
                    "default": null
                },

                "name": {
                    "description": "Developer (company or person) name",
                    "type": "string"
                },

                "supportEmail": {
                    "description": "E-Mail address for support questions",
                    "type": ["string", "null"],
                    "format": "email",
                    "default": null
                },

                "alternateEmail": {
                    "description": "Alternate E-Mail address for support questions",
                    "type": ["string", "null"],
                    "format": "email",
                    "default": null
                },

                "website": {
                    "description": "Developer website",
                    "type": ["string", "null"],
                    "format": "url",
                    "default": null
                },

                "supportPhone": {
                    "description": "Telephone number",
                    "type": ["string", "null"],
                    "default": null
                },

                "founder": {
                    "description": "If the developer was an OUYA founder",
                    "type": "boolean",
                    "default": false
                }
            }
        },

        "contentRating": {
            "description": "Which audience is this game for?",
            "type": "string",
            "enum": [
                "Everyone",
                "9+",
                "12+",
                "17+"
            ]
        },

        "website": {
            "description": "Game website",
            "type": ["string", "null"],
            "format": "url"
        },

        "firstPublishedAt": {
            "description": "When the game has first been published to the world",
            "type": ["string", "null"],
            "format": "date|date-time",
            "default": null
        },

        "inAppPurchases": {
            "description": "If you can buy things in the game",
            "type": "boolean",
            "default": false
        },

        "overview": {
            "description": "FIXME",
            "type": ["string", "null"],
            "default": null
        },

        "premium": {
            "description": "The game has no demo but has to be bought before playing it",
            "type": "boolean",
            "default": false
        },

        "rating": {
            "type": "object",
            "additionalProperties": false,
            "properties": {

                "likeCount": {
                    "description": "Number of likes this game has",
                    "type": "number",
                    "minimum": 0,
                    "default": 0
                },

                "average": {
                    "description": "Average rating for this game",
                    "type": "number",
                    "minimum": 0,
                    "maximum": 5,
                    "default": 0
                },

                "count": {
                    "description": "Number of ratings",
                    "type": "number",
                    "minimum": 0,
                    "default": 0
                }
            }
        },

        "products": {
            "description": "Items that could be bought via the discover store",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "identifier",
                    "name",
                    "localPrice",
                    "originalPrice",
                    "currency"
                ],
                "additionalProperties": false,
                "properties": {

                    "promoted": {
                        "description": "If this product is visible in the ouya discover store",
                        "type": "boolean"
                    },

                    "type": {
                        "description": "Kind of product",
                        "type": "string",
                        "enum": ["entitlement", "consumable", "subscription"],
                        "default": "entitlement"
                    },

                    "identifier": {
                        "description": "Internal key",
                        "type": "string",
                        "examples": [
                            "full_version"
                        ]
                    },

                    "name": {
                        "description": "Human readable name",
                        "type": "string",
                        "examples": [
                            "Unlock full game"
                        ]
                    },

                    "description": {
                        "description": "Explanation of the features you will buy",
                        "type": ["string", "null"],
                        "default": null
                    },

                    "localPrice": {
                        "description": "Current price (maybe discounted)",
                        "type": "number"
                    },

                    "originalPrice": {
                        "description": "Previous price",
                        "type": "number"
                    },

                    "currency": {
                        "description": "Three-letter currency code, depending on the player that was logged in",
                        "type": "string",
                        "enum": ["EUR", "USD"]
                    }
                }
            }
        },

        "relationships": {
            "type": "object",
            "description": "Links to other OUYA applications",
            "additionalProperties": false,
            "properties": {
                "unlocked": {
                    "type": "string",
                    "description": "Package name of unlocked application (full version if this is the demo)"
                },
                "original": {
                    "type": "string",
                    "description": "Package name of original application (demo version if this is the unlocked version)"
                }
            }
        },

        "notes": {
            "description": "Technical notes on the game, e.g. how to get it working or which controllers work.",
            "type": "string"
        }
    }
}

=== zondarg/ouya-game-data/classic/com.ouroborus.muzzle.android.json
{
    "packageName": "com.ouroborus.muzzle.android",
    "title": "Muzzle to Muzzle",
    "description": "Four critters fight claw and fang for dominance in a 2-4 player tactical arena shooter!\n\n- Choose your weapon! Hunt your friends with bolt action rifles, explosives, jump or melee attacks, or watch them die to environmental hazards\n- Fight with four unique critters across eight stock habitats and three distinct game types!\n- Limitless content - make your own habitats with the super easy play-while-you-create editor\n- Keep track of your conquests with user profiles and stats tracking!\n\nUpdate 1.0.1: Adds support for Ouya Everywhere, along with fixing a whole load of bugs, adds a subtle aim assist, button configuration and minor improvements to 'Snowstorm' and 'Skyscraper' habitats.\n\nUpdate 1.0.2: Adds Razer Forge TV support, stats tracking, improved melee mechanics (and new aerial melee), improved tile collision, improved aiming, minor tile improvements, improvements to background painting in edit mode and improved UI.\n\nUpdate 1.0.3: Adds tips to pause menu, and fixes a couple Forge TV crashes, fixes some UI glitches (particularly when loading, saving or deleting habitats).\n\nUpdate 1.0.4: Adds USER PROFILES! Now you can give yourself a name and track your own personal stats and prove once and for all whose the baddest critter in the habitat. Also adds a new lava waterfall tile, removes the broken aim assist, improves melee collision, makes some tutorial clarifications and adds a new 'time spent' stat.",
    "players": [
        1,
        2,
        3,
        4
    ],
    "genres": [
        "Fight!",
        "FPS/Shooter",
        "Multiplayer",
        "Platformer",
        "Retro"
    ],
    "releases": [
        {
            "name": "1.0.5",
            "versionCode": 6,
            "uuid": "477c7460-0e85-412e-85d5-477afcdfd38f",
            "date": "2016-07-19T23:46:51Z",
            "url": "https://archive.org/download/ouya_com.ouroborus.muzzle.android_1.0.5/Muzzle%20to%20Muzzle_1.0.5_com.ouroborus.muzzle.android.apk",
            "size": 28215374,
            "md5sum": "21b66ba982bd86ea279bc9b5a5d7842b",
            "publicSize": 297174,
            "nativeSize": 2141788,
            "cert_fingerprint": "F7:FA:00:B8:77:4E:48:BE:06:FD:B7:87:3A:EF:63:84:73:87:1C:41:7A:05:8C:36:9C:D9:C8:A4:8D:1B:A7:7C",
            "cert_subject": "C = UK, L = Glasgow, O = Ouroborus Games, CN = Michael Hanns"
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/com.ouroborus.muzzle.android/discover",
    "media": [
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.ouroborus.muzzle.android/detail-1",
            "thumb": "http://ouya.cweiske.de/game-images/com.ouroborus.muzzle.android/detail-1-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.ouroborus.muzzle.android/detail-2",
            "thumb": "http://ouya.cweiske.de/game-images/com.ouroborus.muzzle.android/detail-2-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.ouroborus.muzzle.android/detail-3",
            "thumb": "http://ouya.cweiske.de/game-images/com.ouroborus.muzzle.android/detail-3-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.ouroborus.muzzle.android/detail-4",
            "thumb": "http://ouya.cweiske.de/game-images/com.ouroborus.muzzle.android/detail-4-thumb"
        }
    ],
    "developer": {
        "uuid": "588f94ba-1471-4f5d-9616-4fb9b4f13ea9",
        "name": "Ouroboros Softworks",
        "supportEmail": null,
        "supportPhone": null,
        "founder": false
    },
    "contentRating": "12+",
    "website": null,
    "firstPublishedAt": "2016-02-29T16:04:09Z",
    "inAppPurchases": true,
    "overview": "Released in July 2016 by Ouroboros Softworks.",
    "premium": false,
    "rating": {
        "likeCount": 0,
        "average": 2.69,
        "count": 13
    },
    "products": [
        {
            "promoted": true,
            "identifier": "BeerNPizza",
            "name": "a beer and pizza for Ouroborus",
            "description": "This gives you access to the beer mug & pizza tile set in Edit Mode + any future DLC Habitats or Critters the developers release.",
            "localPrice": 8.99,
            "originalPrice": 8.99,
            "currency": "USD"
        }
    ]
}

=== zondarg/ouya-game-data/classic/com.idriscelik.excavatorsimulatorpro.json
{
    "packageName": "com.idriscelik.excavatorsimulatorpro",
    "title": "Excavator Simulator PRO",
    "description": "You can use excavator with this game. Digging, Breaking, Cutting. Destroy builds, load to dump truck. You can use 3 different attachment; Bucket, Rock Breaker and scissors",
    "players": [
        1
    ],
    "genres": [
        "Puzzle/Trivia",
        "Sim/Strategy"
    ],
    "releases": [
        {
            "name": "1.0",
            "versionCode": 0,
            "uuid": "45426ba2-6ed8-46ad-8c89-4ff3fc056b01",
            "date": "2014-08-18T17:59:24Z",
            "url": "https://archive.org/download/ouya_com.idriscelik.excavatorsimulatorpro_1.0/Excavator%20Simulator_1.0_com.idriscelik.excavatorsimulatorpro.apk",
            "size": 65874667,
            "md5sum": "1f7e4971c1fd6118119af9e7d513b59c",
            "publicSize": 168261,
            "nativeSize": 14769772,
            "cert_fingerprint": "F5:C3:11:2F:EF:C2:E3:27:34:A9:58:7F:11:CD:17:4F:F9:B8:3C:0A:C0:1A:98:8F:67:5F:E3:D5:12:5F:83:62",
            "cert_subject": "CN = idris CELIK, OU = idris celik, O = idris Celik, L = istanbul, ST = Turkey, C = 90"
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/discover",
    "media": [
        {
            "type": "video",
            "url": "https://vimeo.com/103530035"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/detail-1",
            "thumb": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/detail-1-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/detail-2",
            "thumb": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/detail-2-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/detail-3",
            "thumb": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/detail-3-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/detail-4",
            "thumb": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/detail-4-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/detail-5",
            "thumb": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/detail-5-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/detail-6",
            "thumb": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/detail-6-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/detail-7",
            "thumb": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/detail-7-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/detail-8",
            "thumb": "http://ouya.cweiske.de/game-images/com.idriscelik.excavatorsimulatorpro/detail-8-thumb"
        }
    ],
    "developer": {
        "uuid": "11111111-43cf-4e8a-ab7b-41d294db7818",
        "name": "idris Celik",
        "supportEmail": "kuklainteractive@gmail.com",
        "supportPhone": null,
        "founder": false
    },
    "contentRating": "Everyone",
    "website": "http://www.idriscelik.com.tr",
    "firstPublishedAt": "2014-08-18T17:59:24Z",
    "inAppPurchases": false,
    "overview": "Released in August 2014 by idris Celik.",
    "premium": true,
    "rating": {
        "likeCount": 0,
        "average": 3.43,
        "count": 14
    },
    "products": [
        {
            "promoted": true,
            "identifier": "Excavator_Simulator",
            "name": "Excavator Simulator PRO",
            "description": "This is a Simulation + Skill game.",
            "localPrice": 0.99,
            "originalPrice": 0.99,
            "currency": "USD"
        }
    ]
}

=== zondarg/ouya-game-data/classic/com.AGameAWeek.PiTSC_I15.json
{
    "packageName": "com.AGameAWeek.PiTSC_I15",
    "title": "Platdude in The Spirit Collector",
    "description": "Platdude has an infestation, so has been laying out traps.\nAnnoyingly, it's not rats, or mice, or even bats.\nGhosts have invaded the mansion, so Platdude's hired out a bunch of handy ghost traps to try to catch them all.\n\nRun past a trap to trigger it off, and insert a blue power-sphere to recharge it.\nCan you protect the mansion?\nOr will Platdude be too scared!?",
    "players": [
        1
    ],
    "genres": [
        "Adventure",
        "Platformer"
    ],
    "releases": [
        {
            "name": "1.3",
            "versionCode": 0,
            "uuid": "7756e417-fbad-485b-9b2f-860b19f8fd40",
            "date": "2016-01-04T22:41:17Z",
            "url": "https://archive.org/download/ouya_com.AGameAWeek.PiTSC_I15_1.3/Collector_1.3_com.AGameAWeek.PiTSC_I15-B9B3.apk",
            "size": 7750229,
            "md5sum": "b9b395edb4b73a0602fe2259a6debea9",
            "publicSize": 157014,
            "nativeSize": 0,
            "cert_fingerprint": "A9:C6:85:6F:07:6C:9C:9F:48:DE:4E:3E:34:62:39:20:80:AF:0C:79:2D:82:C7:5E:93:BF:3E:94:7E:B3:DA:35",
            "cert_subject": "C = GB, ST = GM, L = Bolton, O = agameaweek, OU = Unknown, CN = Jayenkai"
        },
        {
            "name": "1.2",
            "versionCode": 12,
            "uuid": "2658b7b2-a4a4-4693-aa47-6c4c166e5213",
            "date": "2016-01-04T00:00:00Z",
            "url": "https://archive.org/download/ouya_com.AGameAWeek.PiTSC_I15_1.2/Collector_1.2_com.AGameAWeek.PiTSC_I15.apk",
            "size": 7740959,
            "md5sum": "53bcdf7dad8561da3e04a157a467958c",
            "cert_fingerprint": "A9:C6:85:6F:07:6C:9C:9F:48:DE:4E:3E:34:62:39:20:80:AF:0C:79:2D:82:C7:5E:93:BF:3E:94:7E:B3:DA:35",
            "cert_subject": "C = GB, ST = GM, L = Bolton, O = agameaweek, OU = Unknown, CN = Jayenkai"
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/com.AGameAWeek.PiTSC_I15/discover",
    "media": [
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.AGameAWeek.PiTSC_I15/detail-1",
            "thumb": "http://ouya.cweiske.de/game-images/com.AGameAWeek.PiTSC_I15/detail-1-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.AGameAWeek.PiTSC_I15/detail-2",
            "thumb": "http://ouya.cweiske.de/game-images/com.AGameAWeek.PiTSC_I15/detail-2-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.AGameAWeek.PiTSC_I15/detail-3",
            "thumb": "http://ouya.cweiske.de/game-images/com.AGameAWeek.PiTSC_I15/detail-3-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.AGameAWeek.PiTSC_I15/detail-4",
            "thumb": "http://ouya.cweiske.de/game-images/com.AGameAWeek.PiTSC_I15/detail-4-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.AGameAWeek.PiTSC_I15/detail-5",
            "thumb": "http://ouya.cweiske.de/game-images/com.AGameAWeek.PiTSC_I15/detail-5-thumb"
        }
    ],
    "developer": {
        "uuid": "8a1647c2-1d78-4c08-91cf-7916e720fd67",
        "name": "Jayenkai",
        "supportEmail": null,
        "supportPhone": null,
        "founder": false
    },
    "contentRating": "Everyone",
    "website": "http://agameaweek.com",
    "firstPublishedAt": "2015-10-15T22:27:59Z",
    "inAppPurchases": false,
    "overview": "Released in January 2016 by Jayenkai.",
    "premium": false,
    "rating": {
        "likeCount": 0,
        "average": 3.33,
        "count": 9
    }
}
