=== zondarg/ouya-game-data/ouya-game.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://cweiske.de/ouya-game.schema.json",
    "title": "OUYA game metadata",
    "description": "Game data importable in OUYA API servers.",
    "type": "object",

    "required": [
        "packageName",
        "title",
        "releases",
        "discover",
        "media",
        "developer"
    ],
    "additionalProperties": false,
    "properties": {
        "packageName": {
            "description": "Java package names",
            "type": "string",
            "examples": [
                "com.vendor.gamename"
            ]
        },

        "title": {
            "description": "Game name",
            "type": "string"
        },

        "description": {
            "description": "Text describing the game. Newlines (CRLF) allowed",
            "type": "string"
        },

        "players": {
            "description": "How many players can play this game at the same time?",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 1
            }
        },

        "genres": {
            "description": "Categories",
            "type": "array",
            "items": {
                "type": "string",
                "uniqueItems": true,
                "enum": [
                    "Adventure",
                    "App",
                    "Arcade/Pinball",
                    "Card/Casino",
                    "Dual Stick",
                    "Entertainment",
                    "Exclusive",
                    "Fight!",
                    "FPS/Shooter",
                    "Kids List",
                    "Meditative",
                    "Multiplayer",
                    "Music",
                    "Platformer",
                    "Puzzle/Trivia",
                    "Racing",
                    "Retro",
                    "Role-Playing",
                    "Short on Time?",
                    "Sim/Strategy",
                    "Sports",
                    "Utility",
                    "Video",
                    "VIP Room",

                    "Emulator",
                    "2019 GameJam",
                    "2020 GameJam",
                    "2020 Winter GameJam",
                    "2021 Anniversary GameJam",
                    "2021 Winter GameJam",
                    "2022 Winter GameJam",
                    "2023 Anniversary GameJam",
                    "Open Source",
                    "Repackaged",
                    "Tutorials",
                    "Unlocked"
                ]
            }
        },

        "languages": {
            "description": "Language of text/audio content (ISO 639-1)",
            "type": "array",
            "items": {
                "type": "string",
                "uniqueItems": true,
                "enum": [
                    "cs",
                    "da",
                    "de",
                    "el",
                    "en",
                    "eo",
                    "es",
                    "fi",
                    "fr",
                    "hu",
                    "it",
                    "ja",
                    "ko",
                    "nl",
                    "no",
                    "pl",
                    "pt",
                    "ru",
                    "sr",
                    "sv",
                    "th",
                    "tk",
                    "uk",
                    "zh"
                ]
            }
        },

        "releases": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "versionCode",
                    "uuid",
                    "date",
                    "url",
                    "size",
                    "md5sum"
                ],
                "additionalProperties": false,
                "properties": {

                    "broken": {
                        "description": "If the download URL does not work anymore",
                        "type": "boolean",
                        "default": false
                    },

                    "name": {
                        "description": "Human readable version number",
                        "type": "string",
                        "examples": [
                            "1.6"
                        ]
                    },

                    "versionCode": {
                        "description": "APK-internal version code. Run \"aapt dump badging file.apk\", field \"versionCode\"",
                        "type": ["number", "null"]
                    },

                    "uuid": {
                        "description": "Unique ID for the release. Use uuid-gen to get one",
                        "type": "string"
                    },

                    "date": {
                        "description": "When the version has been released",
                        "type": "string",
                        "format": "date|datetime"
                    },

                    "url": {
                        "description": ".apk download link",
                        "type": "string",
                        "format": "url"
                    },

                    "size": {
                        "description": "File size in bytes",
                        "type": "number",
                        "minimum": 1
                    },

                    "md5sum": {
                        "description": "MD5 hash of the .apk file contents",
                        "type": ["string", "null"],
                        "default": null
                    },

                    "publicSize": {
                        "description": "FIXME",
                        "type": "number"
                    },

                    "nativeSize": {
                        "description": "FIXME",
                        "type": "number"
                    },

                    "cert_fingerprint": {
                        "description": "A SHA256 format fingerprint of the signing certificate that was used for this APK. Allows for authorization tracking.",
                        "type": "string",
                        "minLength": 95,
                        "maxLength": 95,
                        "pattern": "^([0-9A-F]{2}:){31}[0-9A-F]{2}$",
                        "examples": [
                            "EF:D5:B9:C0:58:C1:21:ED:97:F3:FD:89:21:12:B6:00:F6:D1:9B:C2:9B:EE:F7:47:40:0C:E0:BB:0D:25:1C:40"
                        ]
                    },

                    "cert_subject": {
                        "description": "The subject name of the signing certificate",
                        "type": "string",
                        "examples": [
                            "C = US, O = Android, CN = Android Debug",
                            "C = US, ST = CA, L = San Francisco, O = SEGA of America, OU = Mobile PD, CN = alben pedroso"
                        ]
                    },

                    "stability": {
                        "description": "What quality of a release this is",
                        "default": "stability",
                        "type": "string",
                        "enum": [
                            "alpha",
                            "beta",
                            "stable"
                        ]
                    }
                }
            }
        },

        "discover": {
            "description": "Main game image. Used in the OUYA discover store. Size 732x412",
            "type": "string",
            "format": "url"
        },

        "media": {
            "description": "Images and videos for the details and apps pages. Can be in any order. The first video is used for the app's 'video' field, all images for app's 'screenshots'.",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "type",
                    "url"
                ],
                "additionalProperties": false,
                "properties": {
                    "type": {
                        "description": "Medium type: image or video",
                        "type": "string",
                        "enum": [
                            "image",
                            "video"
                        ]
                    },
                    "url": {
                        "description": "Image URL or video URL. Vimeo and Youtube URLs supported",
                        "type": "string",
                        "format": "url"
                    },
                    "thumb": {
                        "description": "Small preview image. Size should be 852x479.",
                        "type": "string",
                        "format": "url"
                    }
                }
            }
        },

        "developer": {
            "type": "object",
            "required": [
                "name"
            ],
            "additionalProperties": false,
            "properties": {

                "uuid": {
                    "description": "Unique ID for the developer",
                    "type": ["string", "null"],
                    "default": null
                },

                "name": {
                    "description": "Developer (company or person) name",
                    "type": "string"
                },

                "supportEmail": {
                    "description": "E-Mail address for support questions",
                    "type": ["string", "null"],
                    "format": "email",
                    "default": null
                },

                "alternateEmail": {
                    "description": "Alternate E-Mail address for support questions",
                    "type": ["string", "null"],
                    "format": "email",
                    "default": null
                },

                "website": {
                    "description": "Developer website",
                    "type": ["string", "null"],
                    "format": "url",
                    "default": null
                },

                "supportPhone": {
                    "description": "Telephone number",
                    "type": ["string", "null"],
                    "default": null
                },

                "founder": {
                    "description": "If the developer was an OUYA founder",
                    "type": "boolean",
                    "default": false
                }
            }
        },

        "contentRating": {
            "description": "Which audience is this game for?",
            "type": "string",
            "enum": [
                "Everyone",
                "9+",
                "12+",
                "17+"
            ]
        },

        "website": {
            "description": "Game website",
            "type": ["string", "null"],
            "format": "url"
        },

        "firstPublishedAt": {
            "description": "When the game has first been published to the world",
            "type": ["string", "null"],
            "format": "date|date-time",
            "default": null
        },

        "inAppPurchases": {
            "description": "If you can buy things in the game",
            "type": "boolean",
            "default": false
        },

        "overview": {
            "description": "FIXME",
            "type": ["string", "null"],
            "default": null
        },

        "premium": {
            "description": "The game has no demo but has to be bought before playing it",
            "type": "boolean",
            "default": false
        },

        "rating": {
            "type": "object",
            "additionalProperties": false,
            "properties": {

                "likeCount": {
                    "description": "Number of likes this game has",
                    "type": "number",
                    "minimum": 0,
                    "default": 0
                },

                "average": {
                    "description": "Average rating for this game",
                    "type": "number",
                    "minimum": 0,
                    "maximum": 5,
                    "default": 0
                },

                "count": {
                    "description": "Number of ratings",
                    "type": "number",
                    "minimum": 0,
                    "default": 0
                }
            }
        },

        "products": {
            "description": "Items that could be bought via the discover store",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "identifier",
                    "name",
                    "localPrice",
                    "originalPrice",
                    "currency"
                ],
                "additionalProperties": false,
                "properties": {

                    "promoted": {
                        "description": "If this product is visible in the ouya discover store",
                        "type": "boolean"
                    },

                    "type": {
                        "description": "Kind of product",
                        "type": "string",
                        "enum": ["entitlement", "consumable", "subscription"],
                        "default": "entitlement"
                    },

                    "identifier": {
                        "description": "Internal key",
                        "type": "string",
                        "examples": [
                            "full_version"
                        ]
                    },

                    "name": {
                        "description": "Human readable name",
                        "type": "string",
                        "examples": [
                            "Unlock full game"
                        ]
                    },

                    "description": {
                        "description": "Explanation of the features you will buy",
                        "type": ["string", "null"],
                        "default": null
                    },

                    "localPrice": {
                        "description": "Current price (maybe discounted)",
                        "type": "number"
                    },

                    "originalPrice": {
                        "description": "Previous price",
                        "type": "number"
                    },

                    "currency": {
                        "description": "Three-letter currency code, depending on the player that was logged in",
                        "type": "string",
                        "enum": ["EUR", "USD"]
                    }
                }
            }
        },

        "relationships": {
            "type": "object",
            "description": "Links to other OUYA applications",
            "additionalProperties": false,
            "properties": {
                "unlocked": {
                    "type": "string",
                    "description": "Package name of unlocked application (full version if this is the demo)"
                },
                "original": {
                    "type": "string",
                    "description": "Package name of original application (demo version if this is the unlocked version)"
                }
            }
        },

        "notes": {
            "description": "Technical notes on the game, e.g. how to get it working or which controllers work.",
            "type": "string"
        }
    }
}

=== zondarg/ouya-game-data/classic/com.crescentmoongames.ravensword2.json
{
    "packageName": "com.crescentmoongames.ravensword2",
    "title": "Ravensword: Shadowlands",
    "description": "Ravensword brings unprecedented visuals to the role playing and adventure \r\ngenre. Explore a vast and richly detailed world, gather powerful weapons, collect hundreds of items, increase your skills, and follow a deep storyline to solve the mysteries of the Kingdom of Tyreas.",
    "notes": "Does not work. See https://github.com/ouya-saviors/ouya-game-data/issues/80",
    "players": [
        1
    ],
    "genres": [
        "Adventure",
        "Role-Playing"
    ],
    "releases": [
        {
            "name": "1.26",
            "versionCode": 14,
            "uuid": "a3b39697-2000-40ab-b278-a3a0e9eacb65",
            "date": "2013-06-25T00:00:00Z",
            "url": "https://archive.org/download/ouya_com.crescentmoongames.ravensword2_1.26/Ravensword_%20Shadowlands_1.26_com.crescentmoongames.ravensword2.apk",
            "size": 580059520,
            "md5sum": "e42ed8c849aa52de279ff098df1f658e",
            "cert_fingerprint": "48:2F:62:CE:39:BD:B7:F3:80:1B:C6:A6:8E:46:8F:1D:88:AC:6D:5F:4A:A5:3D:A9:09:A7:3A:3A:EE:45:B6:DB",
            "cert_subject": "O = Crescent Moon Games LLC"
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/com.crescentmoongames.ravensword2/discover",
    "media": [
        {
            "type": "video",
            "url": "https://vimeo.com/87317338"
        }
    ],
    "developer": {
        "uuid": "41746f91-1c25-4857-812c-33c8553b8e56",
        "name": "Crescent Moon Games",
        "supportEmail": "support@crescentmoongames.com",
        "supportPhone": null,
        "founder": false
    },
    "contentRating": "12+",
    "website": "http://www.crescentmoongames.com",
    "firstPublishedAt": "2013-06-25T14:59:05Z",
    "inAppPurchases": true,
    "overview": "Released in June 2013 by Crescent Moon Games.",
    "premium": true,
    "rating": {
        "likeCount": 1451,
        "average": 3.94,
        "count": 992
    },
    "products": [
        {
            "promoted": true,
            "identifier": "iap_full_game",
            "name": "Ravensword: Shadowlands Full Game",
            "description": "Ravensword brings unprecedented visuals to the role playing and adventure genre. ",
            "localPrice": 9.99,
            "originalPrice": 9.99,
            "currency": "EUR"
        }
    ]
}

=== zondarg/ouya-game-data/classic/com.tributegames.Wizorb.json
{
    "packageName": "com.tributegames.Wizorb",
    "title": "Wizorb",
    "description": "The once peaceful Kingdom of Gorudo is threatened by an evil presence. The only hope for salvation is Cyrus, a wizard versed in a secret magic art called Wizorb! Explore many strange places from the derelict monster infested town of Clover to Gorudo Castle atop Cauldron Peak. Danger lurks around every corner so you'll need to keep your wits about you and have quick reflexes in order to survive.",
    "players": [
        1
    ],
    "genres": [
        "Arcade/Pinball",
        "Retro",
        "Role-Playing"
    ],
    "releases": [
        {
            "name": "1.15",
            "versionCode": 0,
            "uuid": "d22ba7fc-0365-46b7-99ee-cd6ed6ecfba7",
            "date": "2013-09-06T14:41:48Z",
            "url": "https://archive.org/download/ouya_com.tributegames.Wizorb_1.15/Wizorb_1.15_com.tributegames.Wizorb.apk",
            "size": 35316831,
            "md5sum": "847d595e887a646f7a7786cad90911dc",
            "publicSize": 0,
            "nativeSize": 0,
            "cert_fingerprint": "FE:C8:BF:8F:98:A8:DE:47:02:34:55:A1:9C:23:E9:9A:B1:D1:A7:76:89:4E:02:AB:20:69:76:4E:30:B8:6F:58",
            "cert_subject": "C = US, O = Android, CN = Android Debug"
        },
        {
            "name": "1.14",
            "versionCode": 1,
            "uuid": "44d6a492-3b9e-44ef-816e-590ef1ada0a4",
            "date": "2013-09-06T00:00:00Z",
            "url": "https://archive.org/download/ouya_com.tributegames.Wizorb_1.14/Wizorb_1.14_com.tributegames.Wizorb.apk",
            "size": 35316839,
            "md5sum": "50d6c96f48aeea0b68f4a4e33069e037",
            "cert_fingerprint": "FE:C8:BF:8F:98:A8:DE:47:02:34:55:A1:9C:23:E9:9A:B1:D1:A7:76:89:4E:02:AB:20:69:76:4E:30:B8:6F:58",
            "cert_subject": "C = US, O = Android, CN = Android Debug"
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/com.tributegames.Wizorb/discover",
    "media": [
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.tributegames.Wizorb/screenshot-1",
            "thumb": "http://ouya.cweiske.de/game-images/com.tributegames.Wizorb/screenshot-1-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.tributegames.Wizorb/screenshot-2",
            "thumb": "http://ouya.cweiske.de/game-images/com.tributegames.Wizorb/screenshot-2-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.tributegames.Wizorb/screenshot-3",
            "thumb": "http://ouya.cweiske.de/game-images/com.tributegames.Wizorb/screenshot-3-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.tributegames.Wizorb/screenshot-4",
            "thumb": "http://ouya.cweiske.de/game-images/com.tributegames.Wizorb/screenshot-4-thumb"
        }
    ],
    "developer": {
        "uuid": "6d531b35-9f5d-42f8-86c4-5c299e3d6f37",
        "name": "Tribute Games Inc.",
        "supportEmail": "info@tributegames.com",
        "supportPhone": null,
        "founder": false
    },
    "contentRating": "Everyone",
    "website": "http://wizorb.com",
    "firstPublishedAt": "2013-03-28T04:10:20Z",
    "inAppPurchases": true,
    "overview": "Released in September 2013 by Tribute Games Inc..",
    "premium": false,
    "rating": {
        "likeCount": 413,
        "average": 4.01,
        "count": 178
    },
    "products": [
        {
            "type": "entitlement",
            "promoted": true,
            "identifier": "wizorbfull",
            "name": "Unlock full game",
            "description": "",
            "localPrice": 0.01,
            "originalPrice": 0.01,
            "currency": "EUR"
        }
    ]
}

=== zondarg/ouya-game-data/classic/com.eggrollgames.matchcolorspaid.json
{
    "packageName": "com.eggrollgames.matchcolorspaid",
    "title": "Kids Color and Shape Card Matching",
    "description": "Teaches color and shape recognition by combining exciting card matching game play with professional narration, fun music and positive feedback. It's fun and easy for kids to use. \r\n\r\nCOLOR IDENTIFICATION\r\n• Match colors to colors\r\n• Match colors to their name\r\n• Match two different pictures with the same color\r\n• Hear the colors as you touch them \r\n\r\nSHAPE RECOGNITION\r\n• Match shapes to shapes\r\n• Match shapes to similarly shaped items\r\n• Match two different pictures with the same shape\r\n• Hear the shapes as you touch them \r\n\r\nCHILD FRIENDLY\r\n• Peek button provides optional hints\r\n• Rewards with balloon popping and positive feedback\r\n• \"Show Me\" game keeps cards face up for easier play \r\n• Items and instructions are professionally narrated\r\n• Parental controls for sound, music and links\r\n• We do not collect personal information from our users\r\n\r\n“As parents and teachers, we believe in friction-free learning for kids of all ages. We strive to build fun experiences with eye-popping visuals, professional narration, catchy music, and lots of positive encouragement.\r\n\r\nThank you for supporting us and making our vision come to life.\r\n\r\nHave fun!!”\r\n\r\n- Blake, Mike & Amanda, Eggroll Games",
    "players": [
        1
    ],
    "genres": [
        "Kids List",
        "Puzzle/Trivia"
    ],
    "releases": [
        {
            "name": "1.0",
            "versionCode": 0,
            "uuid": "9ff201a8-3771-4790-888d-7eeb1554465d",
            "date": "2015-05-05T18:58:33Z",
            "url": "https://archive.org/download/ouya_com.eggrollgames.matchcolorspaid_1.0/Kids%20Card%20Matching%20featuring%20Colors%20and%20Shapes_1.0_com.eggrollgames.matchcolorspaid.apk",
            "size": 33528769,
            "md5sum": "3df3d0e674fe5e1d4253c132bf73055e",
            "publicSize": 1172225,
            "nativeSize": 4188488,
            "cert_fingerprint": "71:F3:0C:E6:3D:8E:01:CE:30:A6:FA:72:B2:0C:76:43:B7:73:90:3A:37:90:55:44:96:19:0A:41:37:2C:24:EF",
            "cert_subject": "C = US, ST = NC, L = Winston-Salem, O = Eggroll Games, OU = Eggroll Games, CN = Michael Oder"
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/discover",
    "media": [
        {
            "type": "video",
            "url": "https://vimeo.com/126131691"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/detail-1",
            "thumb": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/detail-1-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/detail-2",
            "thumb": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/detail-2-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/detail-3",
            "thumb": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/detail-3-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/detail-4",
            "thumb": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/detail-4-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/detail-5",
            "thumb": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/detail-5-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/detail-6",
            "thumb": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/detail-6-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/detail-7",
            "thumb": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/detail-7-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/detail-8",
            "thumb": "http://ouya.cweiske.de/game-images/com.eggrollgames.matchcolorspaid/detail-8-thumb"
        }
    ],
    "developer": {
        "uuid": "f775c8f9-d097-4dad-bf08-f70b7c66b32d",
        "name": "Eggroll Games",
        "supportEmail": null,
        "supportPhone": null,
        "founder": false
    },
    "contentRating": "Everyone",
    "website": "http://eggrollgames.com",
    "firstPublishedAt": "2015-05-05T18:58:33Z",
    "inAppPurchases": false,
    "overview": "Released in May 2015 by Eggroll Games.",
    "premium": true,
    "rating": {
        "likeCount": 0,
        "average": 5,
        "count": 1
    },
    "products": [
        {
            "promoted": true,
            "identifier": "KCSCM",
            "name": "Kids Color and Shape Card Matching",
            "description": "Teaches color and shape recognition by combining exciting card matching game play with engaging feedback.",
            "localPrice": 2.99,
            "originalPrice": 2.99,
            "currency": "USD"
        }
    ]
}
