=== zondarg/ouya-game-data/ouya-game.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://cweiske.de/ouya-game.schema.json",
    "title": "OUYA game metadata",
    "description": "Game data importable in OUYA API servers.",
    "type": "object",

    "required": [
        "packageName",
        "title",
        "releases",
        "discover",
        "media",
        "developer"
    ],
    "additionalProperties": false,
    "properties": {
        "packageName": {
            "description": "Java package names",
            "type": "string",
            "examples": [
                "com.vendor.gamename"
            ]
        },

        "title": {
            "description": "Game name",
            "type": "string"
        },

        "description": {
            "description": "Text describing the game. Newlines (CRLF) allowed",
            "type": "string"
        },

        "players": {
            "description": "How many players can play this game at the same time?",
            "type": "array",
            "items": {
                "type": "number",
                "minimum": 1
            }
        },

        "genres": {
            "description": "Categories",
            "type": "array",
            "items": {
                "type": "string",
                "uniqueItems": true,
                "enum": [
                    "Adventure",
                    "App",
                    "Arcade/Pinball",
                    "Card/Casino",
                    "Dual Stick",
                    "Entertainment",
                    "Exclusive",
                    "Fight!",
                    "FPS/Shooter",
                    "Kids List",
                    "Meditative",
                    "Multiplayer",
                    "Music",
                    "Platformer",
                    "Puzzle/Trivia",
                    "Racing",
                    "Retro",
                    "Role-Playing",
                    "Short on Time?",
                    "Sim/Strategy",
                    "Sports",
                    "Utility",
                    "Video",
                    "VIP Room",

                    "Emulator",
                    "2019 GameJam",
                    "2020 GameJam",
                    "2020 Winter GameJam",
                    "2021 Anniversary GameJam",
                    "2021 Winter GameJam",
                    "2022 Winter GameJam",
                    "2023 Anniversary GameJam",
                    "Open Source",
                    "Repackaged",
                    "Tutorials",
                    "Unlocked"
                ]
            }
        },

        "languages": {
            "description": "Language of text/audio content (ISO 639-1)",
            "type": "array",
            "items": {
                "type": "string",
                "uniqueItems": true,
                "enum": [
                    "cs",
                    "da",
                    "de",
                    "el",
                    "en",
                    "eo",
                    "es",
                    "fi",
                    "fr",
                    "hu",
                    "it",
                    "ja",
                    "ko",
                    "nl",
                    "no",
                    "pl",
                    "pt",
                    "ru",
                    "sr",
                    "sv",
                    "th",
                    "tk",
                    "uk",
                    "zh"
                ]
            }
        },

        "releases": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "versionCode",
                    "uuid",
                    "date",
                    "url",
                    "size",
                    "md5sum"
                ],
                "additionalProperties": false,
                "properties": {

                    "broken": {
                        "description": "If the download URL does not work anymore",
                        "type": "boolean",
                        "default": false
                    },

                    "name": {
                        "description": "Human readable version number",
                        "type": "string",
                        "examples": [
                            "1.6"
                        ]
                    },

                    "versionCode": {
                        "description": "APK-internal version code. Run \"aapt dump badging file.apk\", field \"versionCode\"",
                        "type": ["number", "null"]
                    },

                    "uuid": {
                        "description": "Unique ID for the release. Use uuid-gen to get one",
                        "type": "string"
                    },

                    "date": {
                        "description": "When the version has been released",
                        "type": "string",
                        "format": "date|datetime"
                    },

                    "url": {
                        "description": ".apk download link",
                        "type": "string",
                        "format": "url"
                    },

                    "size": {
                        "description": "File size in bytes",
                        "type": "number",
                        "minimum": 1
                    },

                    "md5sum": {
                        "description": "MD5 hash of the .apk file contents",
                        "type": ["string", "null"],
                        "default": null
                    },

                    "publicSize": {
                        "description": "FIXME",
                        "type": "number"
                    },

                    "nativeSize": {
                        "description": "FIXME",
                        "type": "number"
                    },

                    "cert_fingerprint": {
                        "description": "A SHA256 format fingerprint of the signing certificate that was used for this APK. Allows for authorization tracking.",
                        "type": "string",
                        "minLength": 95,
                        "maxLength": 95,
                        "pattern": "^([0-9A-F]{2}:){31}[0-9A-F]{2}$",
                        "examples": [
                            "EF:D5:B9:C0:58:C1:21:ED:97:F3:FD:89:21:12:B6:00:F6:D1:9B:C2:9B:EE:F7:47:40:0C:E0:BB:0D:25:1C:40"
                        ]
                    },

                    "cert_subject": {
                        "description": "The subject name of the signing certificate",
                        "type": "string",
                        "examples": [
                            "C = US, O = Android, CN = Android Debug",
                            "C = US, ST = CA, L = San Francisco, O = SEGA of America, OU = Mobile PD, CN = alben pedroso"
                        ]
                    },

                    "stability": {
                        "description": "What quality of a release this is",
                        "default": "stability",
                        "type": "string",
                        "enum": [
                            "alpha",
                            "beta",
                            "stable"
                        ]
                    }
                }
            }
        },

        "discover": {
            "description": "Main game image. Used in the OUYA discover store. Size 732x412",
            "type": "string",
            "format": "url"
        },

        "media": {
            "description": "Images and videos for the details and apps pages. Can be in any order. The first video is used for the app's 'video' field, all images for app's 'screenshots'.",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "type",
                    "url"
                ],
                "additionalProperties": false,
                "properties": {
                    "type": {
                        "description": "Medium type: image or video",
                        "type": "string",
                        "enum": [
                            "image",
                            "video"
                        ]
                    },
                    "url": {
                        "description": "Image URL or video URL. Vimeo and Youtube URLs supported",
                        "type": "string",
                        "format": "url"
                    },
                    "thumb": {
                        "description": "Small preview image. Size should be 852x479.",
                        "type": "string",
                        "format": "url"
                    }
                }
            }
        },

        "developer": {
            "type": "object",
            "required": [
                "name"
            ],
            "additionalProperties": false,
            "properties": {

                "uuid": {
                    "description": "Unique ID for the developer",
                    "type": ["string", "null"],
                    "default": null
                },

                "name": {
                    "description": "Developer (company or person) name",
                    "type": "string"
                },

                "supportEmail": {
                    "description": "E-Mail address for support questions",
                    "type": ["string", "null"],
                    "format": "email",
                    "default": null
                },

                "alternateEmail": {
                    "description": "Alternate E-Mail address for support questions",
                    "type": ["string", "null"],
                    "format": "email",
                    "default": null
                },

                "website": {
                    "description": "Developer website",
                    "type": ["string", "null"],
                    "format": "url",
                    "default": null
                },

                "supportPhone": {
                    "description": "Telephone number",
                    "type": ["string", "null"],
                    "default": null
                },

                "founder": {
                    "description": "If the developer was an OUYA founder",
                    "type": "boolean",
                    "default": false
                }
            }
        },

        "contentRating": {
            "description": "Which audience is this game for?",
            "type": "string",
            "enum": [
                "Everyone",
                "9+",
                "12+",
                "17+"
            ]
        },

        "website": {
            "description": "Game website",
            "type": ["string", "null"],
            "format": "url"
        },

        "firstPublishedAt": {
            "description": "When the game has first been published to the world",
            "type": ["string", "null"],
            "format": "date|date-time",
            "default": null
        },

        "inAppPurchases": {
            "description": "If you can buy things in the game",
            "type": "boolean",
            "default": false
        },

        "overview": {
            "description": "FIXME",
            "type": ["string", "null"],
            "default": null
        },

        "premium": {
            "description": "The game has no demo but has to be bought before playing it",
            "type": "boolean",
            "default": false
        },

        "rating": {
            "type": "object",
            "additionalProperties": false,
            "properties": {

                "likeCount": {
                    "description": "Number of likes this game has",
                    "type": "number",
                    "minimum": 0,
                    "default": 0
                },

                "average": {
                    "description": "Average rating for this game",
                    "type": "number",
                    "minimum": 0,
                    "maximum": 5,
                    "default": 0
                },

                "count": {
                    "description": "Number of ratings",
                    "type": "number",
                    "minimum": 0,
                    "default": 0
                }
            }
        },

        "products": {
            "description": "Items that could be bought via the discover store",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "identifier",
                    "name",
                    "localPrice",
                    "originalPrice",
                    "currency"
                ],
                "additionalProperties": false,
                "properties": {

                    "promoted": {
                        "description": "If this product is visible in the ouya discover store",
                        "type": "boolean"
                    },

                    "type": {
                        "description": "Kind of product",
                        "type": "string",
                        "enum": ["entitlement", "consumable", "subscription"],
                        "default": "entitlement"
                    },

                    "identifier": {
                        "description": "Internal key",
                        "type": "string",
                        "examples": [
                            "full_version"
                        ]
                    },

                    "name": {
                        "description": "Human readable name",
                        "type": "string",
                        "examples": [
                            "Unlock full game"
                        ]
                    },

                    "description": {
                        "description": "Explanation of the features you will buy",
                        "type": ["string", "null"],
                        "default": null
                    },

                    "localPrice": {
                        "description": "Current price (maybe discounted)",
                        "type": "number"
                    },

                    "originalPrice": {
                        "description": "Previous price",
                        "type": "number"
                    },

                    "currency": {
                        "description": "Three-letter currency code, depending on the player that was logged in",
                        "type": "string",
                        "enum": ["EUR", "USD"]
                    }
                }
            }
        },

        "relationships": {
            "type": "object",
            "description": "Links to other OUYA applications",
            "additionalProperties": false,
            "properties": {
                "unlocked": {
                    "type": "string",
                    "description": "Package name of unlocked application (full version if this is the demo)"
                },
                "original": {
                    "type": "string",
                    "description": "Package name of original application (demo version if this is the unlocked version)"
                }
            }
        },

        "notes": {
            "description": "Technical notes on the game, e.g. how to get it working or which controllers work.",
            "type": "string"
        }
    }
}

=== zondarg/ouya-game-data/classic/com.thebancast.Love.json
{
    "packageName": "com.thebancast.Love",
    "title": "LOVE",
    "description": "A classically styled platformer with a focus on difficult yet-not-unfair gameplay, a clever respawn mechanic, and a smooth soundtrack.",
    "players": [
        1
    ],
    "genres": [
        "Adventure",
        "Arcade/Pinball",
        "Platformer",
        "Retro"
    ],
    "releases": [
        {
            "name": "0.1.8",
            "versionCode": 0,
            "uuid": "020bb61b-5e10-44d2-95e7-03ae8dd4336a",
            "date": "2013-07-23T16:20:07Z",
            "url": "https://archive.org/download/ouya_com.thebancast.Love_0.1.8/Love_0.1.8_com.thebancast.Love.apk",
            "size": 29618939,
            "md5sum": "8089a491a7e3a705f45f652eba480d2a",
            "publicSize": 0,
            "nativeSize": 0,
            "cert_fingerprint": "61:90:04:A4:2F:95:16:C4:E9:29:BC:50:71:5D:84:84:F7:33:08:11:81:29:94:81:B7:3B:57:1D:C8:D9:B3:67",
            "cert_subject": "C = GB, L = Auchtermuchty, O = Acme Ltd., OU = Development, CN = Privateer"
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/com.thebancast.Love/discover",
    "media": [
        {
            "type": "image",
            "url": "https://archive.org/download/ouya_com.thebancast.Love_0.1.8/yM7ob4AFSP6iGxF3lvVO.jpg",
            "thumb": "https://archive.org/download/ouya_com.thebancast.Love_0.1.8/yM7ob4AFSP6iGxF3lvVO_thumb.jpg"
        },
        {
            "type": "image",
            "url": "https://archive.org/download/ouya_com.thebancast.Love_0.1.8/6RppJFUSGuxFoycukEx4.jpg",
            "thumb": "https://archive.org/download/ouya_com.thebancast.Love_0.1.8/6RppJFUSGuxFoycukEx4_thumb.jpg"
        },
        {
            "type": "image",
            "url": "https://archive.org/download/ouya_com.thebancast.Love_0.1.8/C70U1HdvQrOmKBUIw4sA.jpg",
            "thumb": "https://archive.org/download/ouya_com.thebancast.Love_0.1.8/C70U1HdvQrOmKBUIw4sA_thumb.jpg"
        }
    ],
    "developer": {
        "uuid": "11111111-88c5-4079-8017-bc5d42e653c3",
        "name": "Fred Wood",
        "supportEmail": "thatsmytrunks@gmail.com",
        "supportPhone": null,
        "founder": true
    },
    "contentRating": "Everyone",
    "website": "http://Love-The-Game.com/",
    "firstPublishedAt": "2013-07-23T16:20:07Z",
    "inAppPurchases": false,
    "overview": "Released in July 2013 by Fred Wood.",
    "premium": false,
    "rating": {
        "likeCount": 223,
        "average": 4.21,
        "count": 140
    }
}

=== zondarg/ouya-game-data/classic/com.pigoutproductions.hiddengardenfantasy.json
{
    "packageName": "com.pigoutproductions.hiddengardenfantasy",
    "title": "Hidden Garden Fantasy",
    "description": "Hidden Garden is back with even more beautiful scenes and more amazing music. Continue your journey through the Hidden Gardens in this beautiful hidden object adventure game. Hidden Garden Fantasy is the next title in the Hidden Garden series. Relax and enjoy the gorgeous scenery as you find hundreds of butterflies, birds, lady bugs, and honey bees throughout many breathtaking locations. The stunning visuals are accompanied by four new equally stunning musical compositions.",
    "players": [
        1
    ],
    "genres": [
        "Meditative",
        "Puzzle/Trivia",
        "Short on Time?"
    ],
    "releases": [
        {
            "name": "1.1",
            "versionCode": 2,
            "uuid": "1b16f07e-16fa-4df3-a623-c8bfc2c7d3d5",
            "date": "2014-07-10T21:22:36Z",
            "url": "https://archive.org/download/ouya_com.pigoutproductions.hiddengardenfantasy_1.1/Hidden%20Garden%20Fantasy_1.1_com.pigoutproductions.hiddengardenfantasy.apk",
            "size": 37986416,
            "md5sum": "659f6b75f52c3a2aee10dab2ba59c5ba",
            "publicSize": 291034,
            "nativeSize": 14689140,
            "cert_fingerprint": "95:C4:71:8A:6A:B2:4B:A6:79:EE:4E:0C:5C:A3:40:D9:C8:D0:DE:0C:3D:18:AF:A2:50:DE:AC:41:2E:FE:E5:DF",
            "cert_subject": "C = US, ST = mo, L = houston, O = pigoutproductions, OU = pigoutproductions, CN = William Garrett"
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/com.pigoutproductions.hiddengardenfantasy/discover",
    "media": [
        {
            "type": "video",
            "url": "https://vimeo.com/100833853"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.pigoutproductions.hiddengardenfantasy/detail-1",
            "thumb": "http://ouya.cweiske.de/game-images/com.pigoutproductions.hiddengardenfantasy/detail-1-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.pigoutproductions.hiddengardenfantasy/detail-2",
            "thumb": "http://ouya.cweiske.de/game-images/com.pigoutproductions.hiddengardenfantasy/detail-2-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.pigoutproductions.hiddengardenfantasy/detail-3",
            "thumb": "http://ouya.cweiske.de/game-images/com.pigoutproductions.hiddengardenfantasy/detail-3-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.pigoutproductions.hiddengardenfantasy/detail-4",
            "thumb": "http://ouya.cweiske.de/game-images/com.pigoutproductions.hiddengardenfantasy/detail-4-thumb"
        }
    ],
    "developer": {
        "uuid": "9e40eed8-a159-449e-bc76-da5d13bc1e64",
        "name": "Pig Out Productions, LLC",
        "supportEmail": "support@pigoutproductions.com",
        "supportPhone": null,
        "founder": false
    },
    "contentRating": "Everyone",
    "website": "http://www.pigoutproductions.com",
    "firstPublishedAt": "2014-07-09T22:06:17Z",
    "inAppPurchases": false,
    "overview": "Released in July 2014 by Pig Out Productions, LLC.",
    "premium": true,
    "rating": {
        "likeCount": 0,
        "average": 5,
        "count": 3
    },
    "products": [
        {
            "promoted": true,
            "identifier": "HGFantasy_Full",
            "name": "Hidden Garden Fantasy",
            "description": "Begin your journey through the Hidden Gardens?",
            "localPrice": 1.99,
            "originalPrice": 1.99,
            "currency": "USD"
        }
    ]
}

=== zondarg/ouya-game-data/classic/com.kwnetzwelt.Marbelous.json
{
    "packageName": "com.kwnetzwelt.Marbelous",
    "title": "Marbelous!",
    "description": "In Marbelous! you roll, jump and bounce through more than 35 levels in 6 episodes, each with a unique retro game reference. It is completely free, exclusively on ouya.",
    "players": [
        1
    ],
    "genres": [
        "Adventure",
        "Arcade/Pinball"
    ],
    "releases": [
        {
            "name": "1.2.0",
            "versionCode": 0,
            "uuid": "9da6d654-41fc-4a82-92c6-9114d7b7893f",
            "date": "2013-12-03T07:00:26Z",
            "url": "https://archive.org/download/ouya_com.kwnetzwelt.Marbelous_1.2.0/Marbelous%21_1.2.0_com.kwnetzwelt.Marbelous.apk",
            "size": 41906120,
            "md5sum": "66d99185cb8500b43acf3822df701b66",
            "publicSize": 0,
            "nativeSize": 0,
            "cert_fingerprint": "10:EA:35:17:5B:1F:5A:C6:9E:31:84:DA:DD:2E:B5:A3:0E:1B:F8:CF:B5:6B:5E:74:70:06:67:96:71:B2:4C:3D",
            "cert_subject": "C = de, ST = nrw, L = ob, O = kwnetzwelt, CN = Kai Wegner"
        }
    ],
    "discover": "http://ouya.cweiske.de/game-images/com.kwnetzwelt.Marbelous/discover",
    "media": [
        {
            "type": "video",
            "url": "https://vimeo.com/80252055"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.kwnetzwelt.Marbelous/screenshot-1",
            "thumb": "http://ouya.cweiske.de/game-images/com.kwnetzwelt.Marbelous/screenshot-1-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.kwnetzwelt.Marbelous/screenshot-2",
            "thumb": "http://ouya.cweiske.de/game-images/com.kwnetzwelt.Marbelous/screenshot-2-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.kwnetzwelt.Marbelous/screenshot-3",
            "thumb": "http://ouya.cweiske.de/game-images/com.kwnetzwelt.Marbelous/screenshot-3-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.kwnetzwelt.Marbelous/screenshot-4",
            "thumb": "http://ouya.cweiske.de/game-images/com.kwnetzwelt.Marbelous/screenshot-4-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.kwnetzwelt.Marbelous/screenshot-5",
            "thumb": "http://ouya.cweiske.de/game-images/com.kwnetzwelt.Marbelous/screenshot-5-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.kwnetzwelt.Marbelous/screenshot-6",
            "thumb": "http://ouya.cweiske.de/game-images/com.kwnetzwelt.Marbelous/screenshot-6-thumb"
        },
        {
            "type": "image",
            "url": "http://ouya.cweiske.de/game-images/com.kwnetzwelt.Marbelous/screenshot-7",
            "thumb": "http://ouya.cweiske.de/game-images/com.kwnetzwelt.Marbelous/screenshot-7-thumb"
        }
    ],
    "developer": {
        "uuid": "79e6a138-2a96-46fc-bea3-0e6cf6ba3af5",
        "name": "Alluring Elements",
        "supportEmail": "kwnetzwelt@gmail.com",
        "supportPhone": null,
        "founder": false
    },
    "contentRating": "Everyone",
    "website": "http://www.marbelousgame.com",
    "firstPublishedAt": "2013-12-03T07:00:26Z",
    "inAppPurchases": false,
    "overview": "Released in December 2013 by Alluring Elements.",
    "premium": false,
    "rating": {
        "likeCount": 78,
        "average": 4.04,
        "count": 171
    }
}
